version: "3"
services:
  sillytavern-extras:
    image: cohee1207/sillytavern-extras
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        REQUIREMENTS: requirements.txt
        MODULES: caption,summarize,classify
#        REQUIREMENTS: requirements-complete.txt
#        MODULES: caption,summarize,classify,sd,silero-tts,edge-tts,chromadb
    volumes:
      #- "./chromadb:/chromadb"
      - "./cache:/root/.cache"
      - type: bind
        source: /mnt/user/appdata/sillytavern-extras/api_key.txt
        target: /sillytavern-extras/api_key.txt
    ports:
      - "5100:5100"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: python server.py --listen --enable-modules=caption,summarize,classify
#    command: python server.py --enable-modules=caption,summarize,classify,sd,silero-tts,edge-tts,chromadb
